spring:
    datasource:
        # mysql的配置加载驱动类信息
        driver-class-name: com.mysql.cj.jdbc.Driver
        # mysql的连接信息
        url: jdbc:mysql://10.4.7.100:3308/space-init?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&useSSL=false&serverTimezone=GMT
        # 用户名
        username: root
        # 密码
        password: daohaosima...123

mybatis:
    mapper-locations: classpath:com/master/repository/mapper/*Mapper.xml






